import 'package:flutter/material.dart';
import 'dart:io';
import '../data/models/message_model.dart';
import '../data/repositories/remote_chat_repository.dart';
import '../../../core/services/socket_service.dart';

class ChatProvider extends ChangeNotifier {
  final RemoteChatRepository _repository;
  final SocketService _socketService = SocketService();
  
  // Typing indicator state
  final Map<String, bool> _typingUsers = {};
  
  bool isUserTyping(String userId) => _typingUsers[userId] ?? false;

  ChatProvider(this._repository) {
    // Listen to Socket.IO events
    _socketService.onNewMessage = (data) {
      // Message already handled by Firestore stream
      notifyListeners();
    };
    
    _socketService.onUserTyping = (userId, isTyping) {
      _typingUsers[userId] = isTyping;
      notifyListeners();
    };
  }

  Stream<List<MessageModel>> getMessages(String currentUserId, String otherUserId) {
    return _repository.getMessages(currentUserId, otherUserId);
  }

  Future<void> sendMessage({
    required String senderId,
    required String receiverId,
    required String text,
    String? senderName,
    String? receiverName,
    String type = 'text',
  }) async {
    // Generate chat ID (consistent for both users)
    final chatId = _generateChatId(senderId, receiverId);
    
    // Check socket connection
    if (_socketService.isConnected) {
      _socketService.sendMessage(
        chatId: chatId,
        senderId: senderId,
        receiverId: receiverId,
        message: text,
        type: type,
      );
    } 
    
    // Always save to Firestore for persistence & list view updates (names)
    // Socket might not update Firestore metadata efficiently or at all for list view names
    final message = MessageModel(
      id: '', // Generated by Firestore
      senderId: senderId,
      receiverId: receiverId,
      text: text,
      timestamp: DateTime.now(),
      isRead: false,
      type: type,
      mediaUrl: null,
    );
    
    Map<String, String>? userNames;
    if (senderName != null && receiverName != null) {
       userNames = {
         senderId: senderName,
         receiverId: receiverName,
       };
    }
    
    await _repository.sendMessage(message, userNames: userNames);
  }
  
  String _generateChatId(String userId1, String userId2) {
    final ids = [userId1, userId2]..sort();
    return ids.join('_');
  }
  
  void sendTypingIndicator(String receiverId, bool isTyping) {
    _socketService.sendTypingIndicator(receiverId, isTyping);
  }

  Future<void> sendMediaMessage({
    required String senderId,
    required String receiverId,
    required File file,
    required String type, // 'image', 'video', 'audio'
  }) async {
    try {
      // 1. Upload Media
      final url = await _repository.uploadMedia(file);

      // 2. Send via Socket.IO or Firestore
      final chatId = _generateChatId(senderId, receiverId);
      
      if (_socketService.isConnected) {
        _socketService.sendMessage(
          chatId: chatId,
          senderId: senderId,
          receiverId: receiverId,
          message: '', // Empty message for media
          type: type,
          mediaUrl: url,
        );
      } else {
        // Fallback to Firestore
        debugPrint("⚠️ Socket disconnected. Sending Media via Firestore.");
        final message = MessageModel(
          id: '',
          senderId: senderId,
          receiverId: receiverId,
          text: '',
          timestamp: DateTime.now(),
          isRead: false,
          type: type,
          mediaUrl: url,
        );
        await _repository.sendMessage(message);
      }
    } catch (e) {
      debugPrint("Send Media Error: $e");
      rethrow;
    }
  }
  Future<void> deleteChat(String chatId, String userId) async {
    await _repository.deleteChat(chatId, userId);
    notifyListeners();
  }

  Future<void> deleteMessage(String chatId, String messageId) async {
    await _repository.deleteMessage(chatId, messageId);
    notifyListeners();
  }
  Future<void> deleteMessageForPair(String currentUserId, String otherUserId, String messageId) async {
    final chatId = _generateChatId(currentUserId, otherUserId);
    await deleteMessage(chatId, messageId);
  }
}
